- src/app/app.component.html
- src/app/app.component.scss
- src/app/components/card/card.component.html
- src/app/components/card/card.component.scss
- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.scss
> Improve groups display

- src/app/app.component.scss
- src/app/components/card/card.component.html
- src/app/components/card/card.component.scss
Fix highlights display condition
Fix #56
> Fix Sidenav Position

- package-lock.json
- package.json
- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.ts
- src/settings.yaml
> Use permission to allow dashboard creation

- src/app/components/card/card.component.html
- src/app/components/card/card.component.scss
- src/app/components/card/card.component.ts
- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.ts
- src/settings.yaml
> Highlight user group

- package-lock.json
- src/app/components/dynamic-hub/dynamic-hub.component.ts
> Check user status before trying to get user groups

- src/app/components/dynamic-hub/dynamic-hub.component.ts
> Fetch cards only if force_connect is false

- release.sh
- add ref_branch
- add stage of release
> Enhance release script

- src/app/components/dynamic-hub/dynamic-hub.component.ts
> Fix admin resources path

- CHANGELOG.md
- package-lock.json
- package.json
- src/app/app.module.ts
- src/app/components/card/card.component.html
- src/app/components/hub-action-modal/hub-action-modal.component.html
- src/app/pipes/preview.pipe.ts
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/assets/i18n/template.json
> Read preview images stored as json

- src/app/app.component.scss
- src/app/components/card/card.component.html
- src/app/components/card/card.component.ts
- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.scss
- src/app/components/dynamic-hub/dynamic-hub.component.ts
- src/app/components/static-hub/static-hub.component.html
- src/app/components/static-hub/static-hub.component.scss
> fix: display org for public dashboards

- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.ts
> Feat: display public collection at the end

- src/app/components/dynamic-hub/dynamic-hub.component.ts
- src/settings.yaml
- Fix #197 
- Fix #198 
- Fix #193
> Feat:fix display public if connected

- angular.json
- src/app/app.component.html
- src/app/app.component.scss
- src/app/app.module.ts
- src/app/components/dashboard-search/dashboard-search.component.html
- src/app/components/dashboard-search/dashboard-search.component.scss
- src/app/components/dashboard-search/dashboard-search.component.spec.ts
- src/app/components/dashboard-search/dashboard-search.component.ts
- src/app/components/dynamic-hub/collapse/card-dropdown.component.html
- src/app/components/dynamic-hub/collapse/card-dropdown.component.ts
- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.scss
- src/app/components/dynamic-hub/dynamic-hub.component.ts
- src/app/services/dashboard-search.service.ts
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- src/styles.scss
- src/variables.scss
- close #202
- close #199 
- close #196 
- 
[Capture vidéo du 07-11-2024 16:10:30.webm](https://github.com/user-attachments/assets/da78d4d8-2c24-416f-956a-b96fae39c2f5)
> feat: Feat/hub improvement

- .github/workflows/trivy.yml
- package-lock.json
- package.json
- src/app/services/card.service.ts
> Feat:add display public default value

- src/app/components/dashboard-search/dashboard-search.component.scss
- src/app/components/dynamic-hub/dynamic-hub.component.scss
> enlarge search bar width + remove horizontal scroll

- package-lock.json
- package.json
- src/app/components/card/card.component.ts
- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.scss
- src/app/components/dynamic-hub/dynamic-hub.component.ts
- src/app/services/dashboard-search.service.ts
- src/assets/i18n/en.json
- src/assets/i18n/fr.json
- close #220 
- close #219 
- close #218
- close #221 
French translation:
> Implement hub feedbacks

- .github/workflows/release.yml
- release.sh
> ci: add release github action

- .github/workflows/main.yml
- .github/workflows/release.yml
- .github/workflows/trivy.yml
- package-lock.json
- package.json
- src/app/components/card/card.component.html
- src/app/components/card/card.component.ts
- src/app/components/dynamic-hub/dynamic-hub.component.html
- src/app/components/dynamic-hub/dynamic-hub.component.ts
- src/app/services/card.service.ts
> Feat: some fix to support openid deployment

- src/app/app.module.ts
- src/app/components/collection/collection-detail/collection-detail.component.html
- src/app/components/collection/collection-detail/collection-detail.component.ts
> fix: pressing enter should submit the collection form

- package.json
- src/app/app.module.ts
> fix: correct marker module import

- src/app/services/collection.service.ts
> feat: allow to configure relative ARLAS server url

- src/app/components/collection/collection.component.html
- src/app/components/collection/collection.component.ts
> fix: base collection filter on org owner & shared with
